#!/usr/bin/env python3
"""Demo-Inserate für Handelswelt in Firestore einfügen."""

import urllib.request
import urllib.parse
import json
import time

PROJECT_ID = "handelswelt-703b0"
API_KEY = "AIzaSyBOaHxUSDclEAMWue_MSml5IvaJ4u_GEq8"

# ── Login-Daten hier eintragen ────────────────────────────────
EMAIL = ""
PASSWORT = ""
# ─────────────────────────────────────────────────────────────

FIRESTORE_URL = f"https://firestore.googleapis.com/v1/projects/{PROJECT_ID}/databases/(default)/documents/inserate"

DEMO_INSERATE = [
    {
        "titel": "iPhone 15 Pro Max 256GB – Wie neu",
        "preis": "950 €",
        "ort": "Wien",
        "adresse": "Mariahilfer Straße, Wien",
        "kategorie": "Marktplatz",
        "unterkategorie": "Smartphones",
        "detailUnterkategorie": "",
        "typ": "Privat",
        "beschreibung": "Verkaufe mein iPhone 15 Pro Max in Titan Natur. Nur 3 Monate alt, immer mit Hülle und Schutzglas verwendet. Keine Kratzer, kein Defekt. Originalverpackung und alle Zubehörteile vorhanden.",
        "bild": "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&q=80",
        "bilder": [
            "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&q=80",
            "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&q=80",
        ],
        "zustand": "Wie neu",
        "hersteller": "Apple",
        "garantie": "9 Monate",
        "latitude": 48.1974,
        "longitude": 16.3441,
        "verkaeuferId": "demo",
        "verkaeuferEmail": "demo@handelswelt.at",
        "telefon": "+43 123 456789",
        "telefonSichtbar": True,
        "whatsappAktiv": True,
        "emailSichtbar": True,
        "firmaVerifiziert": False,
    },
    {
        "titel": "BMW 3er 320d xDrive – Vollausstattung",
        "preis": "24.900 €",
        "ort": "Graz",
        "adresse": "Hauptplatz, Graz",
        "kategorie": "Auto & Motor",
        "unterkategorie": "Limousine",
        "detailUnterkategorie": "",
        "typ": "Privat",
        "beschreibung": "BMW 320d xDrive, Baujahr 2020, 89.000 km. Vollausstattung: Navi, Leder, Sitzheizung, LED, Panoramadach. Lückenlos serviciert, Pickerl bis 12/2025. Kein Unfall.",
        "bild": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80",
        "bilder": [
            "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80",
            "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80",
        ],
        "zustand": "Gut",
        "marke": "BMW",
        "modell": "320d xDrive",
        "baujahr": "2020",
        "kilometer": "89000",
        "kraftstoff": "Diesel",
        "getriebe": "Automatik",
        "leistung": "190 PS",
        "farbe": "Alpinweiß",
        "karosserie": "Limousine",
        "unfallfrei": "Ja",
        "latitude": 47.0707,
        "longitude": 15.4395,
        "verkaeuferId": "demo",
        "verkaeuferEmail": "demo@handelswelt.at",
        "telefon": "+43 123 456789",
        "telefonSichtbar": True,
        "whatsappAktiv": True,
        "emailSichtbar": True,
        "firmaVerifiziert": False,
    },
    {
        "titel": "Moderne 3-Zimmer Wohnung – Zentrum Wien",
        "preis": "1.490 €",
        "ort": "Wien",
        "adresse": "Ringstraße 12, Wien",
        "kategorie": "Immobilien",
        "unterkategorie": "Wohnung mieten",
        "detailUnterkategorie": "",
        "typ": "Firma",
        "firmenname": "Immo Wien GmbH",
        "beschreibung": "Helle, moderne 3-Zimmer Wohnung im Herzen Wiens. 78 m², 3. Etage, komplett renoviert, Einbauküche, Parkett. Perfekte Anbindung an öffentliche Verkehrsmittel. Kaution 3 Monatsmieten.",
        "bild": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
        "bilder": [
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
            "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
            "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
        ],
        "immobilienArt": "Wohnung mieten",
        "wohnflaeche": "78",
        "zimmer": "3",
        "kaution": "4.470 €",
        "betriebskosten": "180 €",
        "etage": "3",
        "balkon": "Ja",
        "terrasse": "Nein",
        "garten": "Nein",
        "garage": "Nein",
        "lift": "Ja",
        "keller": "Ja",
        "moebliert": "Nein",
        "latitude": 48.2049,
        "longitude": 16.3703,
        "verkaeuferId": "demo",
        "verkaeuferEmail": "immo@handelswelt.at",
        "telefon": "+43 1 234567",
        "telefonSichtbar": True,
        "whatsappAktiv": False,
        "emailSichtbar": True,
        "firmaVerifiziert": True,
    },
    {
        "titel": "PlayStation 5 Disc Edition + 3 Spiele",
        "preis": "420 €",
        "ort": "Linz",
        "adresse": "Hauptstraße, Linz",
        "kategorie": "Marktplatz",
        "unterkategorie": "Gaming",
        "detailUnterkategorie": "",
        "typ": "Privat",
        "beschreibung": "Verkaufe meine PS5 Disc Edition inkl. 3 Spiele: FIFA 24, God of War Ragnarök, Spider-Man 2. Alles im Topzustand, kaum gespielt. Originalverpackung vorhanden.",
        "bild": "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&q=80",
        "bilder": [
            "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&q=80",
        ],
        "zustand": "Wie neu",
        "hersteller": "Sony",
        "garantie": "Keine",
        "latitude": 48.3069,
        "longitude": 14.2858,
        "verkaeuferId": "demo",
        "verkaeuferEmail": "demo@handelswelt.at",
        "telefon": "+43 123 456789",
        "telefonSichtbar": True,
        "whatsappAktiv": True,
        "emailSichtbar": False,
        "firmaVerifiziert": False,
    },
    {
        "titel": "Softwareentwickler/in gesucht – Wien",
        "preis": "ab 3.500 € brutto",
        "ort": "Wien",
        "adresse": "Donaucity, Wien",
        "kategorie": "Jobs",
        "unterkategorie": "Vollzeit",
        "detailUnterkategorie": "",
        "typ": "Firma",
        "firmenname": "TechSolutions GmbH",
        "beschreibung": "Wir suchen eine/n erfahrene/n Flutter- oder React-Entwickler/in für unser wachsendes Team. Homeoffice möglich. Flexible Arbeitszeiten, modernes Büro, Weiterbildungsbudget.",
        "bild": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80",
        "bilder": [
            "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80",
            "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
        ],
        "jobBerufsbezeichnung": "Softwareentwickler/in",
        "jobGehalt": "ab 3.500 € brutto",
        "jobArbeitsort": "Wien / Homeoffice",
        "jobErfahrung": "Mindestens 2 Jahre",
        "jobBeschaeftigungsart": "Vollzeit",
        "jobHomeoffice": "Teilweise möglich",
        "jobFuehrerschein": "Nicht erforderlich",
        "jobSchichtarbeit": "Tagschicht",
        "jobReisebereitschaft": "Keine",
        "latitude": 48.2378,
        "longitude": 16.4208,
        "verkaeuferId": "demo",
        "verkaeuferEmail": "jobs@techsolutions.at",
        "telefon": "+43 1 987654",
        "telefonSichtbar": True,
        "whatsappAktiv": False,
        "emailSichtbar": True,
        "firmaVerifiziert": True,
    },
    {
        "titel": "Trek Domane SL 5 Rennrad – Größe M",
        "preis": "1.800 €",
        "ort": "Salzburg",
        "adresse": "Getreidegasse, Salzburg",
        "kategorie": "Marktplatz",
        "unterkategorie": "Fahrräder",
        "detailUnterkategorie": "Rennrad",
        "typ": "Privat",
        "beschreibung": "Trek Domane SL 5, Baujahr 2022, Größe M (56 cm). Shimano 105 Schaltung, Carbonrahmen, nur ca. 2.000 km gefahren. Kein Sturz, top Zustand. Zubehör (Pumpe, Schloss) inklusive.",
        "bild": "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&q=80",
        "bilder": [
            "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&q=80",
            "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
        ],
        "zustand": "Sehr gut",
        "hersteller": "Trek",
        "latitude": 47.8004,
        "longitude": 13.0440,
        "verkaeuferId": "demo",
        "verkaeuferEmail": "demo@handelswelt.at",
        "telefon": "+43 123 456789",
        "telefonSichtbar": True,
        "whatsappAktiv": True,
        "emailSichtbar": False,
        "firmaVerifiziert": False,
    },
    {
        "titel": "Samsung 65\" QLED 4K Smart TV",
        "preis": "699 €",
        "ort": "Innsbruck",
        "adresse": "Maria-Theresien-Straße, Innsbruck",
        "kategorie": "Marktplatz",
        "unterkategorie": "Elektronik",
        "detailUnterkategorie": "TV & Audio",
        "typ": "Privat",
        "beschreibung": "Samsung 65 Zoll QLED 4K (Modell QN85B), 1 Jahr alt. Bild ist sensationell, kein einziger Defekt. Verkauf wegen Umzug auf kleinere Wohnung. Originalverpackung vorhanden, Wandhalterung gratis dazu.",
        "bild": "https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&q=80",
        "bilder": [
            "https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&q=80",
        ],
        "zustand": "Sehr gut",
        "hersteller": "Samsung",
        "garantie": "11 Monate",
        "latitude": 47.2692,
        "longitude": 11.3927,
        "verkaeuferId": "demo",
        "verkaeuferEmail": "demo@handelswelt.at",
        "telefon": "+43 123 456789",
        "telefonSichtbar": False,
        "whatsappAktiv": True,
        "emailSichtbar": True,
        "firmaVerifiziert": False,
    },
    {
        "titel": "Golden Retriever Welpen – 8 Wochen",
        "preis": "1.200 €",
        "ort": "St. Pölten",
        "adresse": "St. Pölten, NÖ",
        "kategorie": "Tiere",
        "unterkategorie": "Hunde",
        "detailUnterkategorie": "Welpen",
        "typ": "Privat",
        "beschreibung": "Wunderschöne Golden Retriever Welpen aus seriöser Privatzucht. Beide Elterntiere vorhanden, wesensgetestet. Welpen sind entwurmt, geimpft und gechipt. Aufgewachsen in der Familie mit Kindern.",
        "bild": "https://images.unsplash.com/photo-1552053831-71594a27632d?w=800&q=80",
        "bilder": [
            "https://images.unsplash.com/photo-1552053831-71594a27632d?w=800&q=80",
            "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&q=80",
        ],
        "zustand": "",
        "latitude": 48.2058,
        "longitude": 15.6232,
        "verkaeuferId": "demo",
        "verkaeuferEmail": "demo@handelswelt.at",
        "telefon": "+43 123 456789",
        "telefonSichtbar": True,
        "whatsappAktiv": True,
        "emailSichtbar": False,
        "firmaVerifiziert": False,
    },
    {
        "titel": "Elektriker – Installationsarbeiten & Reparaturen",
        "preis": "65 €/Stunde",
        "ort": "Wien",
        "adresse": "Wien & Umgebung",
        "kategorie": "Dienstleistungen",
        "unterkategorie": "Elektriker",
        "detailUnterkategorie": "Installation",
        "typ": "Firma",
        "firmenname": "Elektro Meier GmbH",
        "beschreibung": "Ihr zuverlässiger Elektriker in Wien. Wir übernehmen alle Elektroinstallationsarbeiten: Neuinstallation, Reparaturen, Sicherungskasten, Smart Home. Notdienst verfügbar!",
        "bild": "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80",
        "bilder": [
            "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80",
            "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
        ],
        "dienstleistungEinsatzgebiet": "Wien und Umgebung (bis 30 km)",
        "dienstleistungPreisProStunde": "65 €",
        "dienstleistungOeffnungszeiten": "Mo–Fr 7–18 Uhr, Sa 8–14 Uhr",
        "dienstleistungAnfahrt": "Ja",
        "dienstleistungNotdienst": "Ja",
        "latitude": 48.2082,
        "longitude": 16.3738,
        "verkaeuferId": "demo",
        "verkaeuferEmail": "elektro@meier.at",
        "telefon": "+43 1 345678",
        "telefonSichtbar": True,
        "whatsappAktiv": True,
        "emailSichtbar": True,
        "firmaVerifiziert": True,
    },
    {
        "titel": "Yamaha MT-07 – 2021 – 8.500 km",
        "preis": "7.200 €",
        "ort": "Klagenfurt",
        "adresse": "Alter Platz, Klagenfurt",
        "kategorie": "Auto & Motor",
        "unterkategorie": "Motorrad",
        "detailUnterkategorie": "Naked Bike",
        "typ": "Privat",
        "beschreibung": "Yamaha MT-07 in matt grau, Baujahr 2021, 8.500 km. Immer professionell gewartet, lückenlos Serviceheft. A2-geeignet mit Drosselung auf 35 kW (rückrüstbar). Pickerl bis 06/2026.",
        "bild": "https://images.unsplash.com/photo-1558980664-769d59546b3d?w=800&q=80",
        "bilder": [
            "https://images.unsplash.com/photo-1558980664-769d59546b3d?w=800&q=80",
            "https://images.unsplash.com/photo-1449426468159-d96dbf08f19f?w=800&q=80",
        ],
        "zustand": "Sehr gut",
        "marke": "Yamaha",
        "modell": "MT-07",
        "baujahr": "2021",
        "kilometer": "8500",
        "kraftstoff": "Benzin",
        "getriebe": "Manuell",
        "leistung": "73 PS",
        "farbe": "Matt Grau",
        "unfallfrei": "Ja",
        "latitude": 46.6228,
        "longitude": 14.3051,
        "verkaeuferId": "demo",
        "verkaeuferEmail": "demo@handelswelt.at",
        "telefon": "+43 123 456789",
        "telefonSichtbar": True,
        "whatsappAktiv": False,
        "emailSichtbar": True,
        "firmaVerifiziert": False,
    },
    {
        "titel": "Vintage Esstisch aus Massivholz – 6 Personen",
        "preis": "380 €",
        "ort": "Graz",
        "adresse": "Lend, Graz",
        "kategorie": "Haus & Garten",
        "unterkategorie": "Möbel",
        "detailUnterkategorie": "Tische",
        "typ": "Privat",
        "beschreibung": "Massiver Eichenholz Esstisch, ca. 100 Jahre alt, Vintage-Stil. 180 x 90 cm, 6 Personen. Selbst abzuholen in Graz. Kleinere Gebrauchsspuren, die den Charme ausmachen.",
        "bild": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
        "bilder": [
            "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
            "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800&q=80",
        ],
        "zustand": "Gebraucht",
        "hersteller": "",
        "latitude": 47.0595,
        "longitude": 15.4346,
        "verkaeuferId": "demo",
        "verkaeuferEmail": "demo@handelswelt.at",
        "telefon": "+43 123 456789",
        "telefonSichtbar": True,
        "whatsappAktiv": True,
        "emailSichtbar": False,
        "firmaVerifiziert": False,
    },
    {
        "titel": "MacBook Pro 14\" M3 Pro – 18 GB RAM",
        "preis": "1.950 €",
        "ort": "Wien",
        "adresse": "1010 Wien",
        "kategorie": "Marktplatz",
        "unterkategorie": "Computer & Laptops",
        "detailUnterkategorie": "Laptop",
        "typ": "Privat",
        "beschreibung": "MacBook Pro 14 Zoll, M3 Pro Chip, 18 GB RAM, 512 GB SSD, Space Schwarz. Gekauft im März 2024, Zustand makellos. Alle Originalzubehörteile inklusive. AppleCare+ bis März 2026.",
        "bild": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80",
        "bilder": [
            "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80",
        ],
        "zustand": "Wie neu",
        "hersteller": "Apple",
        "garantie": "AppleCare+ bis 03/2026",
        "latitude": 48.2082,
        "longitude": 16.3738,
        "verkaeuferId": "demo",
        "verkaeuferEmail": "demo@handelswelt.at",
        "telefon": "+43 123 456789",
        "telefonSichtbar": False,
        "whatsappAktiv": True,
        "emailSichtbar": True,
        "firmaVerifiziert": False,
    },
    {
        "titel": "Nike Air Jordan 1 Retro High OG – Größe 43",
        "preis": "280 €",
        "ort": "Wien",
        "adresse": "Naschmarkt, Wien",
        "kategorie": "Marktplatz",
        "unterkategorie": "Schuhe & Kleidung",
        "detailUnterkategorie": "Sneakers",
        "typ": "Privat",
        "beschreibung": "Nike Air Jordan 1 Retro High OG Chicago, Größe EU 43. Nur 2x getragen, absoluter Topzustand. Originalbox und Papiere vorhanden. Kein Tausch.",
        "bild": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
        "bilder": ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80", "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&q=80"],
        "zustand": "Wie neu", "hersteller": "Nike", "garantie": "",
        "latitude": 48.1982, "longitude": 16.3663,
        "verkaeuferId": "demo", "verkaeuferEmail": "demo@handelswelt.at",
        "telefon": "+43 123 456789", "telefonSichtbar": True, "whatsappAktiv": True, "emailSichtbar": False, "firmaVerifiziert": False,
    },
    {
        "titel": "Audi A4 Avant 2.0 TDI S-line – Österreich-Paket",
        "preis": "19.500 €",
        "ort": "Linz",
        "adresse": "Linz Zentrum",
        "kategorie": "Auto & Motor",
        "unterkategorie": "Kombi",
        "detailUnterkategorie": "",
        "typ": "Privat",
        "beschreibung": "Audi A4 Avant 2.0 TDI, 150 PS, S-line Exterieur, Baujahr 2019, 112.000 km. MMI Navi, LED, Sitzheizung, Einparkhilfe hinten. Pickerl neu, Serviceheft lückenlos.",
        "bild": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80",
        "bilder": ["https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80", "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80"],
        "zustand": "Gut", "marke": "Audi", "modell": "A4 Avant 2.0 TDI", "baujahr": "2019", "kilometer": "112000",
        "kraftstoff": "Diesel", "getriebe": "Manuell", "leistung": "150 PS", "farbe": "Monsungrau", "karosserie": "Kombi", "unfallfrei": "Ja",
        "latitude": 48.3069, "longitude": 14.2858,
        "verkaeuferId": "demo", "verkaeuferEmail": "demo@handelswelt.at",
        "telefon": "+43 123 456789", "telefonSichtbar": True, "whatsappAktiv": False, "emailSichtbar": True, "firmaVerifiziert": False,
    },
    {
        "titel": "Dachgeschosswohnung 2 Zi. – Blick über Wien",
        "preis": "980 €",
        "ort": "Wien",
        "adresse": "Döbling, Wien",
        "kategorie": "Immobilien",
        "unterkategorie": "Wohnung mieten",
        "detailUnterkategorie": "",
        "typ": "Firma",
        "firmenname": "Premium Immo GmbH",
        "beschreibung": "Traumhafte Dachgeschosswohnung mit Dachterrasse und Panoramablick über Wien. 52 m², 2 Zimmer, vollmöbliert, Klimaanlage. Direkt von der Verwaltung, keine Provision.",
        "bild": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
        "bilder": ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80", "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80"],
        "immobilienArt": "Wohnung mieten", "wohnflaeche": "52", "zimmer": "2", "kaution": "2.940 €",
        "betriebskosten": "140 €", "etage": "5 (DG)", "balkon": "Ja", "terrasse": "Ja", "garten": "Nein",
        "garage": "Nein", "lift": "Ja", "keller": "Nein", "moebliert": "Ja",
        "latitude": 48.2489, "longitude": 16.3581,
        "verkaeuferId": "demo", "verkaeuferEmail": "immo@premium.at",
        "telefon": "+43 1 778899", "telefonSichtbar": True, "whatsappAktiv": False, "emailSichtbar": True, "firmaVerifiziert": True,
    },
    {
        "titel": "Kellner/in gesucht – Vollzeit Restaurant Wien",
        "preis": "ab 1.800 € netto",
        "ort": "Wien",
        "adresse": "1010 Wien",
        "kategorie": "Jobs",
        "unterkategorie": "Vollzeit",
        "detailUnterkategorie": "",
        "typ": "Firma",
        "firmenname": "Restaurant Waldviertel GmbH",
        "beschreibung": "Wir suchen eine/n motivierte/n Kellner/in für unser Restaurant in Wien. Erfahrung erwünscht aber nicht Voraussetzung. Gutes Betriebsklima, Trinkgeld, Mitarbeiteressen.",
        "bild": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
        "bilder": ["https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80"],
        "jobBerufsbezeichnung": "Kellner/in", "jobGehalt": "ab 1.800 € netto", "jobArbeitsort": "Wien Innenstadt",
        "jobErfahrung": "Erwünscht", "jobBeschaeftigungsart": "Vollzeit", "jobHomeoffice": "Kein Homeoffice",
        "jobFuehrerschein": "Nicht erforderlich", "jobSchichtarbeit": "Wechselschicht", "jobReisebereitschaft": "Keine",
        "latitude": 48.2082, "longitude": 16.3738,
        "verkaeuferId": "demo", "verkaeuferEmail": "jobs@waldviertel.at",
        "telefon": "+43 1 112233", "telefonSichtbar": True, "whatsappAktiv": True, "emailSichtbar": True, "firmaVerifiziert": True,
    },
    {
        "titel": "Weber Genesis E-335 Gasgrill – Top Zustand",
        "preis": "650 €",
        "ort": "Salzburg",
        "adresse": "Maxglan, Salzburg",
        "kategorie": "Haus & Garten",
        "unterkategorie": "Garten",
        "detailUnterkategorie": "Grills",
        "typ": "Privat",
        "beschreibung": "Weber Genesis E-335 3-Brenner Gasgrill, 2022er Modell. Mit Seitenkocher, Grillrost aus Gusseisen. Nur 1 Saison benutzt, sehr sauber gehalten. Alle Zubehörteile inklusive.",
        "bild": "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80",
        "bilder": ["https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80"],
        "zustand": "Sehr gut", "hersteller": "Weber", "garantie": "Keine",
        "latitude": 47.7934, "longitude": 13.0170,
        "verkaeuferId": "demo", "verkaeuferEmail": "demo@handelswelt.at",
        "telefon": "+43 123 456789", "telefonSichtbar": False, "whatsappAktiv": True, "emailSichtbar": True, "firmaVerifiziert": False,
    },
    {
        "titel": "Siamkatze reinrassig – 12 Wochen",
        "preis": "850 €",
        "ort": "Graz",
        "adresse": "Andritz, Graz",
        "kategorie": "Tiere",
        "unterkategorie": "Katzen",
        "detailUnterkategorie": "Reinrassig",
        "typ": "Privat",
        "beschreibung": "Wunderschöne Siamkatzen aus liebevoller Privatzucht. 2 Kätzinnen verfügbar. Geimpft, entwurmt, gechipt, mit Ahnentafel. Nur in beste Hände abzugeben.",
        "bild": "https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=800&q=80",
        "bilder": ["https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=800&q=80", "https://images.unsplash.com/photo-1548802673-380ab8ebc7b7?w=800&q=80"],
        "zustand": "",
        "latitude": 47.0900, "longitude": 15.4188,
        "verkaeuferId": "demo", "verkaeuferEmail": "demo@handelswelt.at",
        "telefon": "+43 123 456789", "telefonSichtbar": True, "whatsappAktiv": True, "emailSichtbar": False, "firmaVerifiziert": False,
    },
    {
        "titel": "DJI Mini 4 Pro Drohne – Fly More Combo",
        "preis": "780 €",
        "ort": "Innsbruck",
        "adresse": "Innsbruck Zentrum",
        "kategorie": "Marktplatz",
        "unterkategorie": "Elektronik",
        "detailUnterkategorie": "Foto & Video",
        "typ": "Privat",
        "beschreibung": "DJI Mini 4 Pro Fly More Combo mit 3 Akkus, Ladestation, 128 GB SD-Karte. Nur 5 Flüge, absoluter Neuwertzustand. 4K 60fps, Hindernisvermeidung, unter 250g.",
        "bild": "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800&q=80",
        "bilder": ["https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800&q=80"],
        "zustand": "Wie neu", "hersteller": "DJI", "garantie": "10 Monate",
        "latitude": 47.2692, "longitude": 11.3927,
        "verkaeuferId": "demo", "verkaeuferEmail": "demo@handelswelt.at",
        "telefon": "+43 123 456789", "telefonSichtbar": False, "whatsappAktiv": True, "emailSichtbar": True, "firmaVerifiziert": False,
    },
    {
        "titel": "Maler & Anstreicher – Innen & Außen",
        "preis": "45 €/Stunde",
        "ort": "Graz",
        "adresse": "Graz und Umgebung",
        "kategorie": "Dienstleistungen",
        "unterkategorie": "Handwerker",
        "detailUnterkategorie": "Maler",
        "typ": "Firma",
        "firmenname": "Maler Kovač GmbH",
        "beschreibung": "Professionelle Malerarbeiten in Graz und Umgebung. Innenanstriche, Fassaden, Tapezierarbeiten, Lackierungen. Schnell, sauber, zuverlässig. Kostenlose Erstbesichtigung.",
        "bild": "https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=800&q=80",
        "bilder": ["https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=800&q=80"],
        "dienstleistungEinsatzgebiet": "Graz und Umgebung (40 km)", "dienstleistungPreisProStunde": "45 €",
        "dienstleistungOeffnungszeiten": "Mo–Fr 7–17 Uhr", "dienstleistungAnfahrt": "Ja", "dienstleistungNotdienst": "Nein",
        "latitude": 47.0707, "longitude": 15.4395,
        "verkaeuferId": "demo", "verkaeuferEmail": "maler@kovac.at",
        "telefon": "+43 316 123456", "telefonSichtbar": True, "whatsappAktiv": True, "emailSichtbar": True, "firmaVerifiziert": True,
    },
    {
        "titel": "Harley-Davidson Sportster S 1250 – 2022",
        "preis": "13.900 €",
        "ort": "Wien",
        "adresse": "Favoriten, Wien",
        "kategorie": "Auto & Motor",
        "unterkategorie": "Motorrad",
        "detailUnterkategorie": "Cruiser",
        "typ": "Privat",
        "beschreibung": "Harley-Davidson Sportster S, 2022, 121 PS, 9.200 km. Vivid Black, Screamin' Eagle Auspuff, Kofferhalterung. Kein Sturz, Serviceheft vorhanden. Pickerl bis 08/2026.",
        "bild": "https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=800&q=80",
        "bilder": ["https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=800&q=80"],
        "zustand": "Sehr gut", "marke": "Harley-Davidson", "modell": "Sportster S 1250", "baujahr": "2022",
        "kilometer": "9200", "kraftstoff": "Benzin", "getriebe": "Manuell", "leistung": "121 PS", "farbe": "Vivid Black", "unfallfrei": "Ja",
        "latitude": 48.1756, "longitude": 16.3809,
        "verkaeuferId": "demo", "verkaeuferEmail": "demo@handelswelt.at",
        "telefon": "+43 123 456789", "telefonSichtbar": True, "whatsappAktiv": False, "emailSichtbar": True, "firmaVerifiziert": False,
    },
    {
        "titel": "IKEA MALM Schlafzimmer-Set komplett",
        "preis": "320 €",
        "ort": "Wien",
        "adresse": "Simmering, Wien",
        "kategorie": "Haus & Garten",
        "unterkategorie": "Möbel",
        "detailUnterkategorie": "Schlafzimmer",
        "typ": "Privat",
        "beschreibung": "IKEA MALM Schlafzimmer komplett: Doppelbett 180x200 mit Lattenrost, 2 Nachttische, Kommode, Kleiderschrank 4-türig. Eichefarben, guter Zustand. Selbstabbau notwendig.",
        "bild": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&q=80",
        "bilder": ["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&q=80", "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80"],
        "zustand": "Gut", "hersteller": "IKEA", "garantie": "",
        "latitude": 48.1747, "longitude": 16.4181,
        "verkaeuferId": "demo", "verkaeuferEmail": "demo@handelswelt.at",
        "telefon": "+43 123 456789", "telefonSichtbar": True, "whatsappAktiv": True, "emailSichtbar": False, "firmaVerifiziert": False,
    },
    {
        "titel": "Buchhalterin – Teilzeit gesucht – Homeoffice",
        "preis": "ab 2.200 € brutto (TZ)",
        "ort": "Linz",
        "adresse": "Linz / Remote",
        "kategorie": "Jobs",
        "unterkategorie": "Teilzeit",
        "detailUnterkategorie": "",
        "typ": "Firma",
        "firmenname": "Steiner & Partner Steuerberatung",
        "beschreibung": "Wir suchen eine erfahrene Buchhalterin / einen erfahrenen Buchhalter für 20 Std./Woche. DATEV/BMD-Kenntnisse von Vorteil. Homeoffice bis 3 Tage/Woche möglich.",
        "bild": "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
        "bilder": ["https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80"],
        "jobBerufsbezeichnung": "Buchhalterin / Buchhalter", "jobGehalt": "ab 2.200 € brutto", "jobArbeitsort": "Linz / Homeoffice",
        "jobErfahrung": "Mindestens 3 Jahre", "jobBeschaeftigungsart": "Teilzeit", "jobHomeoffice": "Teilweise möglich",
        "jobFuehrerschein": "Nicht erforderlich", "jobSchichtarbeit": "Tagschicht", "jobReisebereitschaft": "Keine",
        "latitude": 48.3069, "longitude": 14.2858,
        "verkaeuferId": "demo", "verkaeuferEmail": "jobs@steiner.at",
        "telefon": "+43 732 445566", "telefonSichtbar": True, "whatsappAktiv": False, "emailSichtbar": True, "firmaVerifiziert": True,
    },
    {
        "titel": "Canon EOS R6 Mark II + RF 24-105mm L",
        "preis": "2.800 €",
        "ort": "Wien",
        "adresse": "Hernals, Wien",
        "kategorie": "Marktplatz",
        "unterkategorie": "Elektronik",
        "detailUnterkategorie": "Foto & Video",
        "typ": "Privat",
        "beschreibung": "Canon EOS R6 Mark II mit RF 24-105mm f/4L IS USM. Auslösezähler: 4.200. Absoluter Topzustand, immer mit Schutzfilter verwendet. Zweiter Akku + Ladegerät + Tasche inklusive.",
        "bild": "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80",
        "bilder": ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80", "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&q=80"],
        "zustand": "Wie neu", "hersteller": "Canon", "garantie": "6 Monate",
        "latitude": 48.2196, "longitude": 16.3277,
        "verkaeuferId": "demo", "verkaeuferEmail": "demo@handelswelt.at",
        "telefon": "+43 123 456789", "telefonSichtbar": False, "whatsappAktiv": True, "emailSichtbar": True, "firmaVerifiziert": False,
    },
]


def firestore_value(val):
    if isinstance(val, bool):
        return {"booleanValue": val}
    if isinstance(val, int):
        return {"integerValue": str(val)}
    if isinstance(val, float):
        return {"doubleValue": val}
    if isinstance(val, str):
        return {"stringValue": val}
    if isinstance(val, list):
        return {"arrayValue": {"values": [firestore_value(v) for v in val]}}
    if isinstance(val, dict):
        return {"mapValue": {"fields": {k: firestore_value(v) for k, v in val.items()}}}
    return {"nullValue": None}


def login_token_holen():
    url = f"https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key={API_KEY}"
    body = json.dumps({"email": EMAIL, "password": PASSWORT, "returnSecureToken": True}).encode()
    req = urllib.request.Request(url, data=body, headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read())["idToken"]


def inserat_einfuegen(inserat, token=None):
    # erstelltAm als Server-Timestamp
    fields = {k: firestore_value(v) for k, v in inserat.items()}
    fields["erstelltAm"] = {"timestampValue": "2024-01-01T00:00:00Z"}

    body = json.dumps({"fields": fields}).encode("utf-8")
    url = f"{FIRESTORE_URL}?key={API_KEY}"

    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"

    req = urllib.request.Request(
        url,
        data=body,
        headers=headers,
        method="POST",
    )

    try:
        with urllib.request.urlopen(req) as resp:
            result = json.loads(resp.read())
            doc_id = result.get("name", "").split("/")[-1]
            print(f"  ✓ {inserat['titel']} → {doc_id}")
            return True
    except Exception as e:
        print(f"  ✗ {inserat['titel']} → Fehler: {e}")
        return False


def main():
    token = None
    if EMAIL and PASSWORT:
        print("Melde an...")
        try:
            token = login_token_holen()
            print("Anmeldung erfolgreich.\n")
        except Exception as e:
            print(f"Anmeldung fehlgeschlagen: {e}\nAbbruch.")
            return
    else:
        print("Keine Login-Daten angegeben. Bitte EMAIL und PASSWORT im Script eintragen.")
        return

    print(f"Füge {len(DEMO_INSERATE)} Demo-Inserate in Firestore ein...\n")
    erfolge = 0
    for inserat in DEMO_INSERATE:
        if inserat_einfuegen(inserat, token=token):
            erfolge += 1
        time.sleep(0.3)

    print(f"\n{erfolge}/{len(DEMO_INSERATE)} Inserate erfolgreich eingefügt.")


if __name__ == "__main__":
    main()
