// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsydYHI_xnFQKIuRf7V8vlwr1KyqksdQg',
    appId: '1:273730391475:web:ec009cff6fda8e046d4fc6',
    messagingSenderId: '273730391475',
    projectId: 'handelswelt-703b0',
    authDomain: 'handelswelt-703b0.firebaseapp.com',
    storageBucket: 'handelswelt-703b0.firebasestorage.app',
    measurementId: 'G-5WP5BG6X4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO0mVFqx4XJ6e7WXhVdNi1DSfDW6tcIg0',
    appId: '1:273730391475:android:f156fa61b98d4d396d4fc6',
    messagingSenderId: '273730391475',
    projectId: 'handelswelt-703b0',
    storageBucket: 'handelswelt-703b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOaHxUSDclEAMWue_MSml5IvaJ4u_GEq8',
    appId: '1:273730391475:ios:ba882d390e15a3456d4fc6',
    messagingSenderId: '273730391475',
    projectId: 'handelswelt-703b0',
    storageBucket: 'handelswelt-703b0.firebasestorage.app',
    iosBundleId: 'com.example.handelswelt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOaHxUSDclEAMWue_MSml5IvaJ4u_GEq8',
    appId: '1:273730391475:ios:ba882d390e15a3456d4fc6',
    messagingSenderId: '273730391475',
    projectId: 'handelswelt-703b0',
    storageBucket: 'handelswelt-703b0.firebasestorage.app',
    iosBundleId: 'com.example.handelswelt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsydYHI_xnFQKIuRf7V8vlwr1KyqksdQg',
    appId: '1:273730391475:web:f6d222c69672bdad6d4fc6',
    messagingSenderId: '273730391475',
    projectId: 'handelswelt-703b0',
    authDomain: 'handelswelt-703b0.firebaseapp.com',
    storageBucket: 'handelswelt-703b0.firebasestorage.app',
    measurementId: 'G-8TN948833B',
  );
}
